; VS向导安装配置
; name: 显示名称
; envname: 环境变量名
; entryfilesrc: 入口文件源位置
; entryfiletarget: 入口文件目标位置
; wizarddatatarget: 向导数据的目标位置
[vs_1]
name=2019
envname=VS160COMNTOOLS
entryfilesrc=vs-entry\2019
entryfiletarget=vc\vcprojects
wizarddatatarget=vc\vcprojects

[vs_2]
name=2022
envname=VS170COMNTOOLS
entryfilesrc=vs-entry\2022
entryfiletarget=vc\vcprojects
wizarddatatarget=vc\vcprojects
